# Generated by Django 3.2.16 on 2022-10-18 10:27

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, verbose_name='username')),
                ('group', models.CharField(max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(max_length=40, verbose_name='email address')),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='customer_photo')),
                ('address', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('company_code', models.CharField(max_length=30)),
                ('sw_customer_id', models.IntegerField(blank=True, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('valid_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberMaster',
            fields=[
                ('memberId', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranSum',
            fields=[
                ('trId', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('fy', models.CharField(choices=[('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029')], max_length=9, verbose_name='fy')),
                ('againstType', models.CharField(choices=[('Shares', 'Shares'), ('Mutual Funds', 'Mutual Funds'), ('Futures & Options', 'Futures & Options'), ('Day Trading', 'Day Trading'), ('Trading', 'Trading')], max_length=20, verbose_name='type')),
                ('sp', models.CharField(max_length=5, verbose_name='scriptId')),
                ('part', models.CharField(max_length=30, verbose_name='script')),
                ('sno', models.IntegerField(blank=True, null=True)),
                ('fmr', models.FloatField(blank=True, null=True)),
                ('isinCode', models.CharField(blank=True, max_length=30, null=True)),
                ('trDate', models.DateField(verbose_name='purchaseDate')),
                ('qty', models.IntegerField(verbose_name='quantity')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=65, verbose_name='rate')),
                ('sVal', models.DecimalField(decimal_places=2, max_digits=65, verbose_name='value')),
                ('sttCharges', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True, verbose_name='stt')),
                ('otherCharges', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True, verbose_name='other')),
                ('noteAdd', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('marketRate', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('marketValue', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('HoldingValue', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('avgRate', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('scriptSno', models.IntegerField(blank=True, null=True)),
                ('empCode', models.CharField(blank=True, max_length=10, null=True)),
                ('clDate', models.DateField(blank=True, null=True)),
                ('clRate', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('clQTY', models.IntegerField(blank=True, null=True)),
                ('clValue', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('clsttCharges', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('clOtherCharges', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('balQty', models.IntegerField(blank=True, null=True)),
                ('dayTrade', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('strategyDate', models.DateField(blank=True, null=True)),
                ('strategyTrigger', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
            ],
        ),
    ]
